version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: liquor-agent-postgres
    environment:
      POSTGRES_USER: liquor_agent
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: liquor_agent_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liquor_agent"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: liquor-agent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: liquor-agent-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://liquor_agent:dev_password@postgres:5432/liquor_agent_dev
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - LOG_LEVEL=INFO
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./outputs:/app/outputs
    command: uvicorn liquor_agent.api.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: liquor-agent-worker
    environment:
      - DATABASE_URL=postgresql://liquor_agent:dev_password@postgres:5432/liquor_agent_dev
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: celery -A liquor_agent.workers.celery_app worker --loglevel=info
    restart: unless-stopped

  frontend:
    image: node:18-alpine
    container_name: liquor-agent-frontend
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

