"""Initial schema - users and customers

Revision ID: f5ba0344c43c
Revises: 
Create Date: 2025-10-22 10:21:31.933716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5ba0344c43c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rfm_segment', sa.String(length=100), nullable=True),
    sa.Column('churn_risk', sa.String(length=50), nullable=True),
    sa.Column('clv_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_night_buyer', sa.Boolean(), nullable=False),
    sa.Column('avg_purchase_hour', sa.Integer(), nullable=True),
    sa.Column('purchase_frequency', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('avg_order_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('success_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('primary_category', sa.String(length=100), nullable=True),
    sa.Column('secondary_category', sa.String(length=100), nullable=True),
    sa.Column('favorite_brands', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_purchase_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_churn_risk'), 'customers', ['churn_risk'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_primary_category'), 'customers', ['primary_category'], unique=False)
    op.create_index(op.f('ix_customers_rfm_segment'), 'customers', ['rfm_segment'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_customers_rfm_segment'), table_name='customers')
    op.drop_index(op.f('ix_customers_primary_category'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_churn_risk'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###

